# Generated by Django 5.2.17 on 2026-08-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('lsas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lsa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lsas.lsaprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.parent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lsa', 'start_time', 'end_time'], name='bookings_bo_lsa_id_e69211_idx'), models.Index(fields=['status', 'start_time'], name='bookings_bo_status_09ed7d_idx')],
            },
        ),
    ]
